name: soundforge
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  polymer: '>=0.15.0 <0.16.0'
  googleapis_auth: any
  core_elements: any
  paper_elements: any
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
